[workspace]
resolver = "2"
members = [
    "altium",
    "altium-macros",
    "adedit",
    "ecadview"
    # "drawsvg",
]
default-members = [
    "altium",
    "altium-macros",
    "adedit"
]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
