[package]
name = "altium"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = "0.26.0"
serde = "1.0.151"
serde-xml-rs = "0.6.0"
xml-rs = "0.8.4"
rust-ini = "0.18"
uuid = { version = "1.2.2", features = ["v1", "v4", "fast-rng"]}
regex = "1.7.0"
lazy_static = "1.4.0"
