[package]
name = "altium-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6.0"
proc-macro2 = "1.0.63"
quote = "1.0.28"
regex = "1.9.1"
syn = "2.0.22"
# syn = { version = "2.0.22", features = ["extra-traits"] }
