[package]
name = "ecad-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
altium = { path = "../altium", version = "0.2.1" }
serde_json = "1.0.117"
regex = "1.10.4"
