name: CI

on:
  push: { branches: [main] }
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: -Dwarnings
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: full

jobs:
  clippy:
    name: Clippy
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: rustup update nightly --no-self-update && rustup default nightly
      - run: rustup component add clippy
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev
      - run: cargo clippy --all-features --all-targets

  test:
    name: Build and test
    timeout-minutes: 15
    strategy:
      fail-fast: true
      matrix:
        include:
        - os: ubuntu-24.04
        # Disabled to keep CI lighter weight
        # - os: macos-15
        # - os: windows-2025
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true
      - run: rustup update stable --no-self-update && rustup default stable
      - uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}
      - run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev
        if: matrix.build == 'linux'
      - run: cargo nextest run
      - run: cargo test --doc

  msrv:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: |
          msrv="$(
            cargo metadata --no-deps --format-version 1 |
              jq -r '.packages | map(select(.name == "altium")) | first | .rust_version'
          )"
          rustup update "$msrv" --no-self-update && rustup default "$msrv"
      - run: cargo check -p altium

  fmt:
    name: Rustfmt
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: rustup update nightly --no-self-update && rustup default nightly
      - run: rustup component add rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all -- --check
      - uses: actions/setup-python@v3

  doc:
    name: Docs
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: rustup update nightly --no-self-update && rustup default nightly
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev
      - run: cargo doc --no-deps
